# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: airbus/server
          dest: node_server.zip
      - name: Generate deployment package
        run: zip -r node_server.zip . -x ".git/*" -x ".github/*" -x ".vscode/*"
      
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')"  
            
      - name: Run beanstalk deploy
        uses: einaregilsson/beanstalk-deploy@v2
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Airbus-user-management
          environment_name: Airbususermanagement-env
          region: us-east-2
          version_label: "${{ steps.timestamp.outputs.date }}"
          deployment_package: node_server.zip
